baseurl = "https://honeycrack7.github.io/blog3/"
DefaultContentLanguage = "ja"

# Language
languageCode = "ja-jp"
hasCJKLanguage = true

publishDir = "docs"
relativeurls = true
canonifyurls = true

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
# theme = "hugo-bootstrap-premium"
theme = "hugo-theme-minos"

toc = true
totop = true

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Category"
	url  = "/categories"
	weight = 0

[[menu.main]]
	name = "Tag"
	url  = "/tags"
	weight = 0
