baseurl = "https://honeycrack7.github.io/blog3/"
languageCode = "en-us"
title = "Strata"
# theme = "hugo-strata-theme"
theme = "hugo-theme-minos"
hasCJKLanguage = true
publishDir = "docs"
relativeurls = false

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Category"
	url  = "/categories"
	weight = 0

[[menu.main]]
	name = "Tag"
	url  = "/tags"
	weight = 0
