---
title: テスト３
author: ~
date: '2017-06-17'
slug: 'test3'
categories: []
tags: []
Categories:
  - Development
  - Golang
Description: ''
Tags:
  - development
  - golang
menu: ''
output: 
  html_document:
    toc: true # table of content true
    toc_float: true
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
#    css: my.css   # you can add your custom css, should be in same folder
  # blogdown::html_page:
  #   toc: true
  #   toc_float: true
  #   theme: united
  #   code_folding: hide
  #   md_extensions: -ascii_identifiers
---

# プロットしてみましょう
プロットのスクリプトを後からやっぱり見たいなって時、ありますよね？

ちなみに、ドキュメントの一番右上にCodeってボタンが出てくる筈です。
これはドキュメントにあるコードを全て表示/非表示にするためのモノです。
```{r}
x <- seq(0, 10, 0.1)
plot(x, exp(x), type = "o")
grid()
```


# フローティングTOC
レスポンシブデザイン対応なので、狭めの環境だとドキュメントの頭に
それなりに幅がある環境なら左にTOCが生成されます。


# タブセクション
ダダ長いドキュメントとはこれでおさらば…

## Sales Report {.tabset}
### Daily
how do you think?
```{r}
plot(cumsum(runif(1000, min = -1, max = 1)), type = "l")
```

### Monthly
how do you think?
```{r}
plot(cumsum(runif(1000, min = -1, max = 1)), type = "l")
```